### ISSUE TITLE
PyPiCloud Behind Load balancer - HTTPS/HTTP conflict

### ISSUE THREAD

**Issue by ZMI-JacobGeiman** [stevearc/pypicloud#100]
I am working on setting up a pypicloud cluster behind a load balancer that is doing ssl termination for me. I am having a problem getting the web pages to load due to the js loading content over a non-ssl connection. I have dug pretty deep into the code, but I cannot identify a way to force the static url that gets set in the base.jinja2 file to use https://hostname/ instead of http://hostname/. 

Is there a way to force the urls that are generated in the template to use https without having an ssl connection between my server and load balancer?

**Comment by ZMI-JacobGeiman** [comment]
I found what I needed here: [Paste Config](http://pythonpaste.org/deploy/modules/config.html)

I used the following settings to force the scheme from behind the reverse proxy
```
[app:main]
filter-with = proxy-prefix

[filter:proxy-prefix]
use = egg:PasteDeploy#prefix
scheme = https
```

**Comment by bruno-geru** [comment]
This should be documented.
