### ISSUE TITLE
Server doesn't return expected format for search

### ISSUE THREAD

**Issue by duardnasty** [stevearc/pypicloud#104]
Hey all,

Currently getting these errors when doing search against our own server (I also did them against the demo server for proof and to post here):
```
[~]$ pip search -i https://pypi.stevearc.com/pypi/ requests
HTTP error 400 while getting https://pypi.stevearc.com/pypi/
Exception:
Traceback (most recent call last):
  File "/opt/clearsky/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/opt/clearsky/lib/python2.7/site-packages/pip/commands/search.py", line 45, in run
    pypi_hits = self.search(query, options)
  File "/opt/clearsky/lib/python2.7/site-packages/pip/commands/search.py", line 62, in search
    hits = pypi.search({'name': query, 'summary': query}, 'or')
  File "/opt/clearsky/lib/python2.7/xmlrpclib.py", line 1240, in __call__
    return self.__send(self.__name, args)
  File "/opt/clearsky/lib/python2.7/xmlrpclib.py", line 1599, in __request
    verbose=self.__verbose
  File "/opt/clearsky/lib/python2.7/site-packages/pip/download.py", line 776, in request
    response.raise_for_status()
  File "/opt/clearsky/lib/python2.7/site-packages/pip/_vendor/requests/models.py", line 862, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 400 Client Error: Bad Request for url: https://pypi.stevearc.com/pypi/
```
It looks to me as though PyPICloud does not have the correct file expected by PIP when it does a POST to search. Has anyone else run into this issue? If so, I'd like to formulate a fix. This is going to be absolutely necessary for us to consider deploying this at work, and it seems to be the only downside we've found so far.

**Comment by pixelbombs** [comment]
I just saw from [issue 101](https://github.com/stevearc/pypicloud/issues/101) that search is not supported. I think I will try fixing this issue for us, and if I do, I will make a pull request. If anyone has any expertise with this issue, any help would be appreciated :D

**Comment by stevearc** [comment]
Yeah search isn't implemented atm, but I think that it might be possible to get a simple version of search working without too much trouble. I would definitely take a look at any PR submitted for it.

The dumb way that might be Good Enough™ for now is to add a `def search(self, text):` to the [ICache](https://github.com/stevearc/pypicloud/blob/d3d394032067b7ca8bc6ead5d3ded4dd4871fb0e/pypicloud/cache/base.py#L17) class and just do a fuzzy string match against the results of `self.distinct()`.

I'm in the middle of a job switch and a move right now, but I may (very, very maybe) have time to look at doing this myself some time in December if you don't get to it.

**Comment by pixelbombs** [comment]
@stevearc Thanks for answering, mate. I'll make a note of your tips when I foray into figuring this out, I'm gonna have to implement it regardless because we're gonna need the functionality, so if I beat you to it (very, very maybe), I'll run the solution by you.

Good luck on your transition!

**Comment by MichaelPalmer1** [comment]
@pixelbombs @stevearc  I've been interested in this for a little while as well. I spent a better part of the day yesterday fooling around with this. Just opened PR #107.
