### ISSUE TITLE
Is it possible to display some Read Me Content for the upload packages

### ISSUE THREAD

**Issue by akashkaveti** [stevearc/pypicloud#105]
We have a pypicloud-docker, For our requirements Is it possible to display some readme content for the packages, on the home page after uploading the package?

**Comment by stevearc** [comment]
At the moment there is no way to store metadata for packages, but there has been [some other interest](https://github.com/stevearc/pypicloud/issues/103) in that feature, so it might happen at some point.

**Comment by ivanvenosdel** [comment]
Also related #15. My "long description" comment is basically the same end as this. One of us requesters is bound to get a moment for a PR eventually. :sweat_smile:

**Comment by stevearc** [comment]
Closing as dupe of #103
