### ISSUE TITLE
Support authenticating through an ECS task role

### ISSUE THREAD

**Issue by vincer** [stevearc/pypicloud#109]
ECS now has support for [roles per-task](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html)

Since pypicloud is still using boto, this isn't supported. [Upgrading to boto3](http://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html#task-iam-roles-minimum-sdk) should fix this.

Any plans to moving to boto3?

**Comment by stevearc** [comment]
I have no immediate plans to migrate to boto3. It's certainly something I would like to do! I've kind of fallen behind on the issues & PRs on this and a couple other of my open source projects, so I'm going to have to catch up with those before I start trying to update to boto3.

**Comment by stevearc** [comment]
Finally got around to migrating to boto3. Released the rewrite in [1.0.0](https://pypi.python.org/pypi/pypicloud/1.0.0)
