### ISSUE TITLE
Installing from server

### ISSUE THREAD

**Issue by andrew0harney** [stevearc/pypicloud#114]
I've this up on a private ec2 server. I uploaded the package OK but trying to run:
    pip install --trusted-host -i http://pypi.contextscout.com:6543/pypi/ <package>

Gives:

Collecting http://pypi.<mydomain>.com:6543/pypi/
  Downloading http://pypi.<mydomain>.com:6543/pypi/
  Cannot unpack file /private/var/folders/pl/s9_f6t_92b5384pqvj51dwcw0000gn/T/pip-rj2trkxb-unpack/pypi (downloaded from /private/var/folders/pl/s9_f6t_92b5384pqvj51dwcw0000gn/T/pip-h21omheh-build, content-type: text/html; charset=UTF-8); cannot detect archive format
Cannot determine archive format of /private/var/folders/pl/s9_f6t_92b5384pqvj51dwcw0000gn/T/pip-h21omheh-build

Does anyone have an idea about what's going on?

**Comment by stevearc** [comment]
I've never seen anything like that. Does the server spit out any errors? If you go to the site in a browser does it appear to be functioning? Can you download the package from the browser and, if so, does the package appear to be intact and correct?

**Comment by josefkorbel** [comment]
Just run into this exact problem, i uploaded few libraries to s3.

When i run:
`sudo pip install nameofpackage --trusted-host --i http://servername.com:8081/simple`

i get
```
Collecting http://servername.com:8081/simple
  Downloading http://servername.com:8081/simple
  Cannot unpack file /tmp/pip-gBsH3H-unpack/simple (downloaded from /tmp/pip-GBilOe-build, content-type: text/html; charset=UTF-8); cannot detect archive format
Cannot determine archive format of /tmp/pip-GBilOe-build
```

However when i run 
`sudo pip install nameofpackage --i http://servername.com:8081/simple`

i get
```
Collecting nameofpackage
  The repository located at servername.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS it is recommended to use HTTPS instead, otherwise you may silence this warning and allow it anyways with '--trusted-host servername.com'.
  Could not find a version that satisfies the requirement pipelines (from versions: )
No matching distribution found for nameofpackage

```

**Comment by stevearc** [comment]
I think this is a case of using the arguments incorrectly. `--trusted-host` expects a value, so it will parse `--i` as the host it should trust. That messes up the parsing of everything else. If you instead do

`sudo pip install nameofpackage --trusted-host servername.com -i http://servername.com:8081/simple`

it should work as expected
