### ISSUE TITLE
The UI deletes the wrong package sometimes 

### ISSUE THREAD

**Issue by doublerainbo** [stevearc/pypicloud#118]
Just want to preface this with that this only occurs sometimes, which makes it hard to track down, but it's as follows.

So if I select a version of a package to delete, the row disappears as expected, but when I refresh, the package comes back into the list. As this screenshot shows below, the three steps that I would see:

![screen shot 2017-04-10 at 3 45 20 pm](https://cloud.githubusercontent.com/assets/3181717/24885752/1966b3c0-1e05-11e7-9807-5dd2ad6d7a96.png)

I did some digging on the backend and I find that the package is indeed deleted off of s3, but the dynamo entry storing the filename is kept in place. Instead another file is removed instead. So now we'd have an orphaned file in s3 that does not have anything pointing to it in dynamo, and an entry in dynamo pointing to an invalid location.

I haven't found a surefire way to repro, but I have found that it is easier to repro if there are two packages of the same version, like a sdist and a wheels distribution of the same revision. It could be because they were uploaded at similar times (but I have no evidence to back this claim up).

I'm currently using 0.4.4 with a s3 and dynamo backend. If I can help provide any more info please let me know! Thanks and great work on this project!

**Comment by stevearc** [comment]
Thanks for the detailed report! This is really weird. I'll dig into it and see if I can get a repro

**Comment by stevearc** [comment]
Fixed and released in [0.4.6](https://pypi.python.org/pypi/pypicloud/0.4.6) and [0.5.1](https://pypi.python.org/pypi/pypicloud/0.5.1).
