### ISSUE TITLE
Failing S3 uploads, probably after upgrade

### ISSUE THREAD

**Issue by dirkdevriendt** [stevearc/pypicloud#120]
We are using the docker image (which works great, btw, thanks for that!).

But it recently started eating new versions (pip upload returned success, but the versions did not appear), presumably after our infra refreshed the container with a new image version (this rebuilds the cache, so I don't think the SQLite DB is to blame).
The logs mentioned S3 Access errors:
```<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
<AWSAccessKeyId>AKIA**...**GJVA</AWSAccessKeyId>
<StringToSign>
PUT
ah8NR**...**Mb/Qn6zFg==
application/octet-stream
Wed, 19 Apr 2017 16:49:33 GMT
x-amz-meta-name:my-package-name
x-amz-meta-summary:None
x-amz-meta-version:0.0.1
/my-bucket-name/c2f8/my-package-name/my.package.name-0.0.1.tar.gz
</StringToSign>
<SignatureProvided>qQhyX+pg+**...**DgwKhKbdTA=</SignatureProvided>
<StringToSignBytes>...</StringToSignBytes>
<RequestId>...</RequestId>
<HostId>...</HostId>
</Error>
```

Changes to the config (both in config.ini and on the Amazon S3 bucket config) were no help AFAICT, so in the end only a return to version 0.4.4 (didn't try other versions) seemed to enable uploads again.

**Comment by stevearc** [comment]
To confirm, you were seeing this failure in version 0.5.x? And that signature error was thrown during the package upload?

If that's the case, I suspect it may be due to a boto or botocore update. I just shipped the docker containers for 0.4.6 and 0.5.1, so they would have pulled in the latest and it may have broken something. I'll try to dig into it this weekend.

**Comment by dirkdevriendt** [comment]
Yes, I pulled in the current "latest" version to make sure I did not have an intermediate broken build and I saw this behaviour in what I assume is 0.5.1

I can do some testing if that would help or you have a specific question, but I obviously have to either setup a test environment or wait for a quiet moment :-)

**Comment by stevearc** [comment]
I'll try to repro it first, but if I can't I may ask for some help. Thanks!

**Comment by stevearc** [comment]
I think that your upload problems are the same as #119, and I think the fix for that is to change the url that you're using from `http://my.pypicloud.com/pypi` to `http://my.pypicloud.com/simple`.

The S3 signature errors are something else entirely that I couldn't reproduce. Could you try the above fix and see if you're still having issues?

**Comment by stevearc** [comment]
Also I released [0.5.2](https://pypi.python.org/pypi/pypicloud/0.5.2) which should fix the issue with uploading without any changes to the url. Still curious about the S3 errors though

**Comment by dirkdevriendt** [comment]
Thanks! Since I'm the only one reporting this, it is probably specific to our installation. I'll try out the new version when I have the opportunity, set up a reproducable case if the issue still occurs and report back.

**Comment by davidglvn** [comment]
Hi,
I'm using 0.5.2 with docker (and iam role) and have S3 signature error. Had it with setup command at the beginning, but now it works(had bad .pypirc file). But upload from UI give me the S3 error:
```
Traceback (most recent call last):
  File "/env/local/lib/python2.7/site-packages/pyramid/router.py", line 233, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/env/local/lib/python2.7/site-packages/pyramid/router.py", line 208, in invoke_subrequest
    response = handle_request(request)
  File "/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 120, in tm_tween
    reraise(*exc_info)
  File "/env/local/lib/python2.7/site-packages/pyramid_tm/__init__.py", line 93, in tm_tween
    response = handler(request)
  File "/env/local/lib/python2.7/site-packages/pyramid/tweens.py", line 62, in excview_tween
    reraise(*attrs['exc_info'])
  File "/env/local/lib/python2.7/site-packages/pyramid/tweens.py", line 22, in excview_tween
    response = handler(request)
  File "/env/local/lib/python2.7/site-packages/pyramid/router.py", line 155, in handle_request
    view_name
  File "/env/local/lib/python2.7/site-packages/pyramid/view.py", line 612, in _call_view
    response = view_callable(context, request)
  File "/env/local/lib/python2.7/site-packages/pyramid/config/views.py", line 181, in __call__
    return view(context, request)
  File "/env/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 389, in attr_view
    return view(context, request)
  File "/env/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 367, in predicate_wrapper
    return view(context, request)
  File "/env/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 438, in rendered_view
    result = view(context, request)
  File "/env/local/lib/python2.7/site-packages/pyramid_duh/params.py", line 306, in param_twiddler
    return fxn(**scope)
  File "/env/local/lib/python2.7/site-packages/pypicloud/views/simple.py", line 36, in upload
    version=version, summary=summary)
  File "/env/local/lib/python2.7/site-packages/pypicloud/cache/base.py", line 112, in upload
    self.storage.upload(new_pkg, data)
  File "/env/local/lib/python2.7/site-packages/pypicloud/storage/s3.py", line 184, in upload
    key.set_contents_from_string(data.read(), encrypt_key=self.use_sse)
  File "/env/local/lib/python2.7/site-packages/boto/s3/key.py", line 1426, in set_contents_from_string
    encrypt_key=encrypt_key)
  File "/env/local/lib/python2.7/site-packages/boto/s3/key.py", line 1293, in set_contents_from_file
    chunked_transfer=chunked_transfer, size=size)
  File "/env/local/lib/python2.7/site-packages/boto/s3/key.py", line 750, in send_file
    chunked_transfer=chunked_transfer, size=size)
  File "/env/local/lib/python2.7/site-packages/boto/s3/key.py", line 951, in _send_file_internal
    query_args=query_args
  File "/env/local/lib/python2.7/site-packages/boto/s3/connection.py", line 668, in make_request
    retry_handler=retry_handler
  File "/env/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/env/local/lib/python2.7/site-packages/boto/connection.py", line 940, in _mexe
    request.body, request.headers)
  File "/env/local/lib/python2.7/site-packages/boto/s3/key.py", line 884, in sender
    response.status, response.reason, body)
S3ResponseError: S3ResponseError: 403 Forbidden
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><AWSAccessKeyId>ASIA***************</AWSAccessKeyId><StringToSign>PUT
Jvr6******************==
application/octet-stream
Tue, 25 Apr 2017 08:43:19 GMT
x-amz-meta-name:package
x-amz-meta-summary:None
x-amz-meta-version:0.0.1
x-amz-security-token:FQoDYX***...***T7xwU=
/bucket-name/92b5/package/package-0.0.1.tar.gz</StringToSign><SignatureProvided>Bu4Ww**********************=</SignatureProvided><StringToSignBytes>***...***</StringToSignBytes><RequestId>358B************</RequestId><HostId>uhnI***********************************************************************=</HostId></Error>
```

**Comment by dirkdevriendt** [comment]
I'm terribly sorry. This may have been the -important- missing tidbit in my bug report. I have indeed also tested the upload using the UI and the error is likely to have come from there. I had originally assumed the failure to upload via the pip client and the UI would have had the same root cause, but as @stevearc indicated this is probably not the case...

**Comment by stevearc** [comment]
Interesting. So to clarify, you get this S3 signature error when uploading using the UI, but *not* when you `python setup.py upload`?

**Comment by triplepoint** [comment]
I just got a very similar S3 forbidden error in a different scenario:
- pypicloud set up with S3 storage, Postgres cache, fallback mode: cache
- Uploaded a locally built pip package with `twine`, against the /simple/ API.  This package depended on a 3rd party package in pypi.python.org
- Attempted to `pip install` the just-uploaded package from pypicloud

Weirdly, the initial package publishing with `twine` worked fine.  I could verify the logs showed no errors, a record showed up in the cache DB, and the package itself showed up in the S3 bucket.

But the S3 error occurred on `pip install` when pypicloud attempted to fetch and cache the fallback 3rd party dependency.

So is there some difference in how S3 credentials are handled for caching missed fallback packages, vs package publishing?

**Comment by stevearc** [comment]
Okay, I found one thing that was definitely causing problems and fixed it in [0.5.3](https://pypi.python.org/pypi/pypicloud/0.5.3).

Let me know if this is still causing problems for you

**Comment by dirkdevriendt** [comment]
Fabulous!
Just tested the upgrade from v0.4.4 to v0.5.3 and AFAICT this worked with no remaining issues and I can confirm both UI and `python setup.py upload` uploads work fine on the new version.

I will leave this open for other people to comment (read: leave compliments for a job wel done :-)), but as far as I am concerned the issue can be closed.

**Comment by pctSW1** [comment]
I'm actually having the same problem with version 1.0.10 all works except for installing of package with an S3 error of SignatureDoesNotMatch
