### ISSUE TITLE
Wrong S3 url for the upload package

### ISSUE THREAD

**Issue by danielfranca** [stevearc/pypicloud#145]
Hey guys,
I've just installed PypiCloud, and first, it is an amazing tool, great work :)

I'm having an issue while setting up S3 as storage...
It works fine when I use the Filesystem for storage, but when I try using S3, it uploads fine... but when I try to install(via pip) or download(clicking on the download link) I get an error similar to this:

**The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.**
And the correct endpoint is **https://mybucket.s3.amazonaws.com**
Instead, the generated URL is **https://s3.amazonaws.com/mybucket**

If I just change this in the URL it works...

I've looked into the settings checking if I could change this path somehow, but couldn't find anything.

Any idea or workaround? (or maybe I'm missing some S3 settings to fix it?)

Thanks,
Daniel

**Comment by danielfranca** [comment]
UPDATE:
The issue is that my bucket has dots on it, changing it to a non-dotted one it works :)
Would be nice if it accepts dots, or at least to mention it on the documentation.

Thanks

**Comment by stevearc** [comment]
Ah, this was changed somewhat recently in #136 because it appeared that putting a period in the bucket name was functioning now. I'll have to dig into it a little more and find out why it sometimes works and sometimes fails
