### ISSUE TITLE
Feature request: adding IBM cloud storage

### ISSUE THREAD

**Issue by tjhgit** [stevearc/pypicloud#146]
Hi thanks for this great python application. 

I would like to use IBM object store instead of S3 amazon storage. The following python library does all the interfacing with IBM object store: https://github.com/IBM/ibm-cos-sdk-python.

Can you give me a hint of how to best proceed? 
Shortly looking at the code I see, that:
1) The file and S3 classes are subclasses of IStorage
2) It seems that _lambda_handler.py and lambda_scripts.py use the s3.py functionality. I do not think IBM cloud supports lambdas.

I guess the most simple option would be to create a new subclass of IStorage and that's it?!
I do not see where the lambda_scripts.py is used in the code...

Thanks!

**Comment by tjhgit** [comment]
... and I just have to check that the test_storage.py runs through?

**Comment by stevearc** [comment]
You shouldn't have to worry about the lambda stuff; that's just for some experimental functionality. You should be able to just create a new subclass of [IStorage](https://github.com/stevearc/pypicloud/blob/c1458a8ace71cd628b7062d0fc403070a62399ea/pypicloud/storage/base.py#L5) and implement the abstract methods. Then put the dotted path to your new class in [pypi.storage](http://pypicloud.readthedocs.io/en/latest/topics/configuration.html#pypi-storage) and it should work.

Right now test_storage.py is only going to run tests on the current storage systems, but it should be relatively straightforward to copy the S3 test and adapt it for your needs. It's only a unit test, so it won't catch most of the real interactions between the server and the object store.

**Comment by stevearc** [comment]
#189 added support for GCS. IBM cloud support could follow the same pattern.
