### ISSUE TITLE
Hanging while Rebuilding cache using Postgresql backend

### ISSUE THREAD

**Issue by protheantom** [stevearc/pypicloud#147]
I think there is a regression of #26 in version 1.0.0 and 1.0.1

With S3 backend and PostgreSQL cache empty, pypicloud hangs at "Cache is empty. Rebuilding from storage backend..."

I've tested the versions 0.4.5 and 0.5.6 and worked fine.

```
...
*** Operational MODE: preforking ***
Loading paste environment: config:/etc/pypicloud/config.ini
INFO 2017-12-19 15:33:57,214 [botocore.credentials] Found credentials in environment variables.
INFO 2017-12-19 15:33:57,442 [botocore.vendored.requests.packages.urllib3.connectionpool] Starting new HTTPS connection (1): s3.eu-west-1.amazonaws.com
INFO 2017-12-19 15:33:57,648 [pypicloud.cache.base] Cache is empty. Rebuilding from storage backend...
```

Thanks for the work, pypicloud looks great ;)

**Comment by stevearc** [comment]
Thanks for the report! I got a fix in. It should go out in the next release.
