### ISSUE TITLE
Easier way to manage user using the web UI

### ISSUE THREAD

**Issue by danielfranca** [stevearc/pypicloud#149]
Hi guys,
Not sure if it is an issue.

But I switched to using sql as the backend for authentication
As the documentation suggests I was expecting to be able to manage users from the web UI

> You can opt to store all user and group permissions inside a SQL database. The advantages are that you can dynamically change these permissions using the web interface. 

But the only thing I can change there now is the packages permissions/groups, is that expected?

I couldn't even find out how to create a new user but admin, I don't see any option to add new user or register in the login screen (except for the first one)

There is any easy way to add user management on the web UI?

**Comment by stevearc** [comment]
This has been on my TODO list for a while. I'd like to add a way for the admin to create new users in the admin interface. Right now the way it works is if you go to pypicloud and log out, you have the option to register. Then the admin can approve you. It's not great; I'll see about adding this feature in the next release
