### ISSUE TITLE
AJAX request errors are completely invisible to the user

### ISSUE THREAD

**Issue by underyx** [stevearc/pypicloud#151]
We deleted a user, and their name disappeared from the list as expected. A month later, however, we found out said user still had access to everything they saw before. As it turns out, the deletion request was failing (due to #150) but the UI was completely ignoring this and it just removed the user from the list in the browser when the request was sent. Upon refresh, the user reappears in the list.

**Comment by stevearc** [comment]
oof. I'll take a look and see if I can fix the deletion problem and surface errors better
