### ISSUE TITLE
SQLite cache reload from S3 yields empty DB

### ISSUE THREAD

**Issue by thehesiod** [stevearc/pypicloud#152]
this is with 1.0.1, after tracing through the code it seems that the sqlalchemy session was never getting committed.  Once I added that all my old modules popped up.  I'll submit a PR shortly

**Comment by stevearc** [comment]
I have some unreleased changes in the 1.0 branch. You should check if ca3c49ae4e8d707b9fc2e763d1fde2ad3f1ac9ec fixes the issue before working on a PR

**Comment by thehesiod** [comment]
hah, that was my fix :)

**Comment by thehesiod** [comment]
when do you expect to publish a release with that fix?  Should I just git install from that 1.0 branch?

**Comment by stevearc** [comment]
I don't have a lot of time to work on pypicloud anymore. I was going to try to get some other fixes in before the release, but I could go ahead and push out what I have. In that case I could probably get it out Thursday night.

**Comment by stevearc** [comment]
Released in [1.0.2](https://pypi.python.org/pypi/pypicloud/1.0.2)
