### ISSUE TITLE
Feature request: Signup flow improvements

### ISSUE THREAD

**Issue by underyx** [stevearc/pypicloud#156]
The user creation feature in the admin panel is a very welcome change! There's a few ways to improve it though I believe.

- Since the admin enters the password, the user account is technically compromised from the get-go. I would therefore suggest enforcing a password change upon first login.
- As there's no need for admins to know about the user's password, might as well remove the possibility and hassle of setting and handling it manually. PyPI Cloud could just generate a one time password for enrolling a new user.
- At this point it's probably easier to dissociate these admin initiated sign-ups from the regular user creation and login flow, and instead use something link invite links with one-time-use tokens.

Of course, these are super low-priority quality of life improvements. I mostly just wanted to note down these thoughts & ideas. 👯

**Comment by stevearc** [comment]
Closing this since the signup token functionality was added. Feel free to re-open if this still doesn't address your needs
