### ISSUE TITLE
Prometheus metrics endpoint

### ISSUE THREAD

**Issue by jpds** [stevearc/pypicloud#162]
Hello, would it be possible to integrate something like https://pypi.python.org/pypi/pyramid-prometheus into pypicloud? We're running this on multiple containers on our Kubernetes platform and this would be a neater way to monitor it.

**Comment by stevearc** [comment]
I think that should be fairly straightforward. If you install the package alongside pypicloud you should just be able to add a [pyramid.includes](https://docs.pylonsproject.org/projects/pyramid/en/latest/narr/environment.html#including-packages) section to the config file, and it should add the middleware that you want. It looks like that package is also looking for `prometheus.port`, and you'll need to expose that with docker
