### ISSUE TITLE
DynamoDB table creation race condition

### ISSUE THREAD

**Issue by sdanbury** [stevearc/pypicloud#167]
Hello!

For redundancy, I am running three pypicloud servers that all use the same dynamo db tables and s3 bucket. If I bring them up all at the same time and the dynamo db tables don't exist, they will fight eachother to create/delete the tables in an endless loop until one of them wins.

Other than bringing up one server to do the dynamo db creation, then bringing up the other two, do you have any other suggestions please?

**Comment by rtkmhart** [comment]
I would love a flag or attribute to prevent pypicloud from creating the Dynamo tables and instead pass in the names of the tables. I deploy pypicloud in ECS (Docker) with Cloudformation and can easily create the tables in the CFN template, add autoscaling rules on them etc, and it sucks to do that after the deploy manually. That would solve this problem too.

**Comment by stevearc** [comment]
One thing that you could do now is try setting [db.graceful_reload = true](http://pypicloud.readthedocs.io/en/latest/topics/cache.html#id3). That'll prevent pypicloud from deleting the tables at all, though the initial step of loading packages into the cache may take more time and throughput.

Likewise, for the problem that @rtkmhart mentioned, right now it should be possible to create the tables elsewhere, they just have to have a specific name (and you'll also have to use `db.graceful_reload = true` to avoid removing & replacing it on first startup). I could add a feature that allows you to customize what the names of the tables are, which might make this experience better.

I could also add an option to the cache that allows you to disable the first-load empty cache detection. Right now pypicloud will check the cache and see if it's empty the first time you start it up. If it is empty, it'll scan through the storage backend and fill the cache. If I include a switch to disable that, you could either disable it for 2/3 servers or you could disable on all servers and manually click the button to reload the cache if you're starting with an empty cache.

Do any of the potential features I mentioned sound like something you would want? Is there a different way that it could work that you think would be better?

**Comment by sdanbury** [comment]
For my original issue, the graceful reload flag should be enough, thanks a lot.

I like the ability to create buckets with custom names and be able to pass those in. I loved the "just set everything up for me approach" the first time around, it was all so easy, but also having this option would be very useful.

**Comment by stevearc** [comment]
I believe all reported issues are resolved. Re-open if this is not the case
