### ISSUE TITLE
Does not properly detect if s3 bucket exists

### ISSUE THREAD

**Issue by sdanbury** [stevearc/pypicloud#169]
Was trying to use the latest docker image with a dynamo db cache and s3 bucket for storage. It kept crashing for no apparent reason, turns out, there was a typo in the s3 bucket name in the config which meant it was trying to use a bucket that didn't exist.

Would be good to have a critical log message telling me the bucket doesn't exist.

**Comment by stevearc** [comment]
I guess that's what I get for relying on the network request to return a decent error message when something goes wrong. I'll see what I can do about surfacing a better error message

**Comment by sdanbury** [comment]
Thanks Steven!
