### ISSUE TITLE
Feature request: unsigned URLs

### ISSUE THREAD

**Issue by acordiner** [stevearc/pypicloud#173]
As far as I can tell there is no option to use unsigned S3 URLs in pypicloud. It would be really useful to allow this for public S3 buckets, because URL signing is slow and prevents client HTTP caching.

**Comment by stevearc** [comment]
Sounds like a good idea. Note that you can get this behavior today by setting up a CloudFront distribution for your bucket and leaving the [storage.cloud_front_key_id](http://pypicloud.readthedocs.io/en/latest/topics/storage.html#storage-cloud-front-key-id) blank.

**Comment by acordiner** [comment]
Excellent! Looking forward to seeing this merged.
