### ISSUE TITLE
DynamoDB backed pypicloud won't allow packages without a description

### ISSUE THREAD

**Issue by sdanbury** [stevearc/pypicloud#174]
We are trying to upload a package.tar.gz to pypicloud that doesn't have a description in the setup.py file.

We are using [twine](https://pypi.org/project/twine/) to upload these packages to pypicloud:

```
twine upload --repository-url pypi.example.com -u ***** -p ***** package.tar.gz
```

Because we are using DynamoDB as a caching layer for pypicloud, we get the following error when trying to upload packages in this way:

```
dynamo3.exception.DynamoDBError: ValidationException: One or more parameter values were invalid: An AttributeValue may not contain an empty string
```

I believe this is because DynamoDB doesn't allow for empty strings, [which is documented as one of it's limitations](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html#limits-attributes).

If we upload to pypicloud using `python setup.py upload`, a description of `UNKNOWN` is automatically added to the package if one is not provided in the setup.py, so we don't see this error.

We only see this error when we are trying to upload already-packaged packages that have no description, using twine.

Is it even plausible to mimic the functionality of `python setup.py` and add an `UNKNOWN` package description at the point of insertion to DynamoDB? Would be great to hear your thoughts on this.

**Comment by stevearc** [comment]
Eh, the easy solution is to just not try to upload an empty string to Dynamo. This should be handled by the DynamoDB library, but it wasn't, so it's time for hacks.
