### ISSUE TITLE
How to limit the permission for authenticated  user

### ISSUE THREAD

**Issue by FrankJian** [stevearc/pypicloud#177]
stevearc:
   i have a question. how to limit the permission for authenticated  user? just means only give upload package permission to  authenticated  user but no deleted permission, only admin can delete packages.

**Comment by stevearc** [comment]
Hi Frank. Right now the only permissions that exist are for "read" and "write". Deleting a package falls under the "write" permissions and there isn't any way to separate them at the moment.

It's possible to change the permission structure to support that, but it would be a good bit of work to build it in a way that's backwards-compatible. The relevant areas are the delete API call
https://github.com/stevearc/pypicloud/blob/f221a0e40a1c9a8ab750f10316fc52d5ae84ab1e/pypicloud/views/api.py#L117-L125
The location where we check & optionally prevent the overwriting of packages
https://github.com/stevearc/pypicloud/blob/f221a0e40a1c9a8ab750f10316fc52d5ae84ab1e/pypicloud/cache/base.py#L115-L116
And then a new delete permission would have to be worked into the auth backends. There are a lot of locations, but these would have to be updated to include 'delete' in the return values
https://github.com/stevearc/pypicloud/blob/f221a0e40a1c9a8ab750f10316fc52d5ae84ab1e/pypicloud/access/base.py#L335-L370

I'm happy to look at a pull request for this, but I probably won't spend any time on it myself unless it becomes a popular request.

**Comment by stevearc** [comment]
This was requested again in #259, and I ended up adding a config option to disable the ability to delete packages entirely. This may serve your purpose
