### ISSUE TITLE
520 Unknown Error when refresh the main page

### ISSUE THREAD

**Issue by FrankJian** [stevearc/pypicloud#178]
Hi , 
  i always occurred the issue when i refresh the main page, i use the ldap to authenticate to it.
here is the details ::

520 Unknown Error
_fetch_user() takes exactly 2 arguments(1 given)

**Comment by FrankJian** [comment]
issue only happened when i refresh the page with the account log in. .

**Comment by ggarbutante** [comment]
Has this been fixed?

**Comment by stevearc** [comment]
#192 should fix the immediate stacktrace, but there was an exception being thrown prior to that that I have no information about still. If you are experiencing this problem and have a repro, please let me know and send me some debugging information!
