### ISSUE TITLE
Failed to install with python=3.6

### ISSUE THREAD

**Issue by Justin318** [stevearc/pypicloud#179]
Unable to install pypicloud using "pip install pypicloud" on windows because of missing package pycrypto.

**Comment by stevearc** [comment]
This was the kick I needed to get off of pycrypto and figure out how to use [cryptography](https://cryptography.io/en/latest/) for everything. I *think* that using cryptography will make it play nice on Windows, but even if it doesn't at least it's a crypto library that's been updated more recently than 2013.

I'll cut a new release as soon as I get a chance. If you have time before then, it would be helpful if you can try installing the 1.0 branch on windows and confirm that it works properly.
`pip install git+https://github.com/stevearc/pypicloud.git@1.0`
