### ISSUE TITLE
Health check endpoint should probe external backends

### ISSUE THREAD

**Issue by jpds** [stevearc/pypicloud#181]
It'd be ideal if the `/health` endpoint checked that the connection to either S3/DynamoDB was successful, this way something like Kubernetes could move unhealthy containers that can't access these (for whatever reason) out of its load-balancing rotation.

**Comment by stevearc** [comment]
This is a good idea. I realize now that the commit I added checks the access & cache backends, but doesn't yet test the S3 connection. I'll add that in a follow-up
