### ISSUE TITLE
LDAP referrals lead to authentication issues

### ISSUE THREAD

**Issue by joaovictortr** [stevearc/pypicloud#182]
Our network uses Windows Active Directory to authenticate users, with a secondary and tertiary AD server in place. When querying one of the servers, an issue occurs with the [LDAP referral](http://ldapwiki.com/wiki/LDAP%20Referral) address provided by the LDAP server (Windows AD). In the current implementation (version 1.0.6, at the time of writing), [LDAP referrals are not disabled by default, nor there is an option to disable them](https://github.com/stevearc/pypicloud/blob/master/pypicloud/access/ldap_.py#L78).

When referrals are not disabled, the LDAPBackend does not manage to find the user I'm looking for in the LDAP tree. However, using ```ldapsearch```, with the same credentials and base DN, I've managed to find the same user on the tree.

The error message is attached in [err_pypiserver_ldap_referral.log](https://github.com/stevearc/pypicloud/files/2142136/err_pypiserver_ldap_referral.log), and the configuration in 
[pypiserver_config.txt](https://github.com/stevearc/pypicloud/files/2142137/pypiserver_config.txt).

Disabling the LDAP referrals seem to remedy the issue. Even though I do not think referrals should be disabled by default, there should be an option to disable them in such cases.

**Comment by stevearc** [comment]
Fixed by #184
