### ISSUE TITLE
Add flag to turn multiple results error in LDAP search for an user into a warning

### ISSUE THREAD

**Issue by joaovictortr** [stevearc/pypicloud#183]
Our network uses Windows Active Directory to authenticate users, with a secondary and tertiary AD server in place. The AD servers are also used by the LDAP server for authentication. However, when filtering for an user, there are multiple results, even though the record is the same.

It would be sufficient for authentication if there is at least one user that matches the username and password in the LDAP, even if there are multiple results for the same user. Would it be acceptable to add a flag to make the [multiple results error](https://github.com/stevearc/pypicloud/blob/master/pypicloud/access/ldap_.py#L120) into a warning?

**Comment by stevearc** [comment]
Fixed in #184
