### ISSUE TITLE
wrong json redirect

### ISSUE THREAD

**Issue by thehesiod** [stevearc/pypicloud#186]
when navigating to: https://{HOST_NAME}/pypi/{MODULE_NAME}/json on a pypicloud server with redirects enabled, it 3xx's to: https://pypi.org/simple/{MODULE_NAME}/ which is wrong because the ends up being the XML page and not the JSON page.  The redirect needs to be: https://pypi.org/pypi/fiona/json

**Comment by stevearc** [comment]
Fixed in #188
