### ISSUE TITLE
LDAP Groups

### ISSUE THREAD

**Issue by dclar43** [stevearc/pypicloud#199]
I see that there's no support for associating LDAP users with groups due to there not being a way to identify a user's groups via LDAP currently.
  
I'm curious if you would be willing to allow support for associating manually defined groups, similar to those defined in the [Config File](https://pypicloud.readthedocs.io/en/latest/topics/access_control.html#config-file) method, with LDAP users.  
  
For example  
  
```  
# USERS
user.dclar43
user.donlan

# GROUPS
group.sharkfest =
    dclar43
group.brotatos =
    donlan

# PACKAGES
package.django_unchained.user.dclar43 = rw
package.django_unchained.group.sharkfest = rw

package.polite_requests.group.authenticated = r
package.polite_requests.group.brotatos = rw

package.pyramid_head.group.brotatos = rw
package.pyramid_head.group.everyone = r  
```  
  
Note: I didn't include the user's FQDN because the `auth.ldap.user_dn_format` setting should already cover this.  
  
I'm interesting in using this project as an intranet-available service for other devs within my company. For that to work out I'd really need a way to prevent users from stepping on each other's toes or messing with others' packages.  
  
Without that I would have to set it up as a service only available to me, which isn't an issue but I think this could be much more useful as a generally available service.

**Comment by stevearc** [comment]
I'm on board to add group support to the LDAP backend. Before we jump in and do the configuration with the config file, it's worth seeing if we can do it better using the actual LDAP backend. When LDAP support was first added it was implemented quite differently than it is today, and that's most of the reason why there's no group support yet. If you look at how admin detection works with [`auth.ldap.admin_field` and `auth.ldap.admin_value`](https://pypicloud.readthedocs.io/en/latest/topics/access_control.html#auth-ldap-admin-field), would the same mechanism work for you to detect group membership?

**Comment by dclar43** [comment]
For the general use case that would probably do the job.    
  
I'll explain my specific use case a bit more:  
  
My company isn't software or developer oriented and as such our LDAP schema doesn't consider software developers as a concept.  
  
Considering how granular the potential set of groups, packages, and permissions could get the cost of maintaining the LDAP schema might be too much.  
  
e.g. if I were to add a new package and I wanted only myself and `UserA` to have write access then I'd need to request that IT create a new group and add us into it.   
  
And if I wanted to publish a package maintained only by myself, and not all users who belong to the `software_team_b` group, I think more fine-tuned control would be needed.  
  
Worst case scenario each package would require an equivalent LDAP group/attribute.  
  
So in the end having the ability to assign LDAP users to locally-defined groups would be a requirement for my, and likely others', scenario.

**Comment by stevearc** [comment]
Yeah that makes sense; LDAP can be unwieldy for use cases like this. I think it'll be possible to do a hybrid approach, where LDAP is used for all the user auth, but group and permissions configuration is deferred to a different system. I'll see if I can get something working before Thanksgiving hits

**Comment by stevearc** [comment]
Put up a simple implementation. Will cut a new release soon
