### ISSUE TITLE
Support for GCS default credentials.

### ISSUE THREAD

**Issue by josephglanville** [stevearc/pypicloud#205]
It would be nice if PyPiCloud could be configured to use the default credentials of the environment if none are provided. This is the default of the Google API client if `GOOGLE_APPLICATION_CREDENTIALS` is not set.
I propose altering the GCS authentication path in 2 ways, firstly instead of directly creating the client using `storage.Client.from_service_account_json` instead use the default credentials path, i.e: `storage_client = storage.Client()` and secondly changing the code to set the environment variable if it's not set, i.e `os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = service_account_json_filename` as to maintain backwards compatibility with specifying the credentials file in config rather than environment.

This should allow PyPiCloud when launched on GCP instances or GKE containers that use service-account-assigner to authenticate using granted service account credentials. Aside from being less configuration it has some security benefits as service accounts issued this way are easy to rotate.

**Comment by stevearc** [comment]
This sounds pretty reasonable to me (knowing nothing about GCS myself). I'd be happy to review a pull request with those changes!

**Comment by josephglanville** [comment]
Great, will probably open at PR sometime in the coming week. :)

**Comment by SimonStJG** [comment]
I needed this the other day so I wrote up a quick bodge - see https://github.com/SimonStJG/pypicloud/commit/837f565c78aa6d8fc8df6c270e5b869dbd5f0353  It's not ideal though because you have to workaround https://github.com/googleapis/google-auth-library-python/issues/50

Happy to polish it up into a PR if it's useful to you.

**Comment by josephglanville** [comment]
Ahh I ran into this but didn't locate the workaround, great work.

**Comment by bjgbeelen** [comment]
I'm looking for the same functionality, was about to fix this myself. 
It would be great to have @SimonStJG 's change as part of the code and in a new release!

**Comment by fgoroncy** [comment]
Is this still being worked on? I want to run pypicloud on Google Cloud Run with the assigned identity. There is no easy way of providing the application credentials in a secure way otherwise. @SimonStJG commit looks good but has not found its way back into this repo.

**Comment by stevearc** [comment]
If there's a fix does someone want to open a PR?

**Comment by SimonStJG** [comment]
@stevearc raised a PR for this - https://github.com/stevearc/pypicloud/pull/226
