### ISSUE TITLE
Ability to change S3 endpoint_url

### ISSUE THREAD

**Issue by mamoit** [stevearc/pypicloud#209]
Currently it is only possible to use aws with the s3 module.
If the `endpoint_url` can be set in the boto3 configuration, it should be pretty simple to use other S3 compatible object stores such as the likes of minio or ceph.

**Comment by stevearc** [comment]
You can set the endpoint_url. Pypicloud will pass through configuration options to boto if you prefix them with `storage.`.
https://pypicloud.readthedocs.io/en/latest/topics/storage.html#s3

**Comment by mamoit** [comment]
thanks, I tried it and didn't get it working in useful time, then I moved to the GCS integration (faster downloads than having minio in the middle).
