### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by stevearc** [stevearc/pypicloud#21]

**Comment by meunierd** [comment]
I'd be happy to look into this if someone's willing to go over the work involved/knows the present status of this ticket.

**Comment by stevearc** [comment]
The biggest blocker here used to be that boto (and thus the S3 api) didn't support python 3. But now with [boto3](https://github.com/boto/boto3) out and (hopefully) stable, we could migrate over to using that API and the rest of it should be super simple.

**Comment by meunierd** [comment]
The original boto already supports Python 3 these days as far as I know, but I think the transition is encouraged anyways.

**Comment by meunierd** [comment]
https://github.com/meunierd/pypicloud/tree/feature/python3 I've started the work of porting to Python3. The biggest problem with the test suite right now is that python3 has no equivalent of `assertItemsEqual`. Any thoughts on how to approach that?

**Comment by stevearc** [comment]
I think python 3 has something similar called [assertCountEqual](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertCountEqual). I've handled this in the past by doing this somewhat gross monkey patch: https://github.com/mathcamp/flywheel/blob/master/tests/__init__.py

**Comment by bladeoflight16** [comment]
Is this still open? The wheel on PyPI (https://pypi.python.org/pypi/pypicloud/0.3.5) says it's compatible with Python 2 and 3 (the `py2.py3` parts).

**Comment by stevearc** [comment]
That may be misleading; I'm pretty sure there's still a couple trailing pieces that don't play nice with py3. Thanks for the bump, I'll take a look into this soon and see if I can get the remaining bits migrated.

**Comment by stevearc** [comment]
I've begun work to support python 3. It's sadly not as straightforward as I was hoping it would be, but you can follow the progress here: https://github.com/mathcamp/pypicloud/pull/76

**Comment by stevearc** [comment]
We did it team.
