### ISSUE TITLE
running pypicloud behind https proxy

### ISSUE THREAD

**Issue by rexroof** [stevearc/pypicloud#211]
I run pypicloud in a kubernetes cluster in a docker container. 
my kubernetes load balancer provides HTTPS to the pypicloud service.

I've been falling down the python docs rabbit hole trying to figure out the proper configuration to get the pypicloud site to work properly in HTTPS without actually terminating the HTTPS itself. 

this doc:  https://pypicloud.readthedocs.io/en/latest/topics/deploy.html
mentions "paste middleware", and links to an invalid link:  http://pythonpaste.org/deploy/modules/config.html
I believe the updated url is this:

https://pastedeploy.readthedocs.io/en/latest/modules/config.html
and that has zero information. 

are there updated docs someplace?  any guidance for this?

**Comment by stevearc** [comment]
You can find the old version of those docs here: https://web.archive.org/web/20150214132033/http://pythonpaste.org/deploy/modules/config.html

If all you need is HTTPS (no prefixing or anything) it *should* be pretty straightforward. [As of 2.0.8](https://uwsgi-docs.readthedocs.io/en/latest/Changelog-2.0.8.html#automatically-manage-http-x-forwarded-proto), uWSGI supports the `X-Forwarded-Proto` header.

**Comment by rexroof** [comment]
thanks steven.    I'm a little confused by the relationship between pypicloud and pastescript and uwsgi. 

the issue we're having is that pypicloud is loading all of its js and css resources over http instead of https. 

from my experience with hosting other applications, I'm under the impression that I need to tell pypicloud its protocol and hostname so that it properly renders pages that load the correct resources?

**Comment by stevearc** [comment]
You're correct, you *do* need to tell pypicloud the protocol so that it generates the static resource and other links properly. You don't need any middleware or anything fancy for this to work. The standard way to do this is to configure your proxy to send a [X-Forwarded-For](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For) or [X-Forwarded-Proto](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-Proto) header. Pyramid will automatically read that header and configure its links correctly.

Quick example:
```
$ curl -s localhost:6543/ | grep link
<link href="http://localhost:6543/static/1.0.11/css/lib/bootstrap-3.0.3.min.css" rel="stylesheet">
    <link href="http://localhost:6543/static/1.0.11/css/lib/font-awesome-4.0.3/css/font-awesome.min.css" rel="stylesheet">
    <link href="http://localhost:6543/static/1.0.11/css/base.css" rel="stylesheet">
```
```
$ curl -s -H "X-Forwarded-Proto: https" localhost:6543/ | grep link
<link href="https://localhost:6543/static/1.0.11/css/lib/bootstrap-3.0.3.min.css" rel="stylesheet">
    <link href="https://localhost:6543/static/1.0.11/css/lib/font-awesome-4.0.3/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://localhost:6543/static/1.0.11/css/base.css" rel="stylesheet">
```

**Comment by rexroof** [comment]
I installed an echoserver and diagnosed that we were sending the x-forwarded-proto header already.
then I realized that our container wasn't running uwsgi, it was running pserve. 
I installed uwsgi in the container image and updated the config.  SSL appears to be working now. 

now if I could move the health endpoint to /healthz 
maybe I should open a new issue.  ;)
