### ISSUE TITLE
Python 3.7

### ISSUE THREAD

**Issue by asgoel** [stevearc/pypicloud#212]
Does `pypicloud` support 3.7? I don't see it listed in the tox file or `setup.py` file as a supported version. Usually the major blocker to upgrading to `3.7` is the fact that `async` became a reserved keyword, and you need to change it everywhere you use it but it is not defining an async function. Not sure if that applies here.

**Comment by stevearc** [comment]
I wasn't sure so I updated the tests 2a75be063bdb4abe452eb9261241290adddd631c
Looks like it does!
