### ISSUE TITLE
Ability to deny cache_update per repository

### ISSUE THREAD

**Issue by mamoit** [stevearc/pypicloud#214]
I'm running a pypi server as cache for pypi.org (trying not to DoS them :smile:), while also hosting some private repos.
This private repos have some clashes in terms of names with ones that exist on pypi.org.
Since every user has the ability to `update_cache`, to get the latest and greatest version of a package on pypi, they can also pull a private package from pypicloud and accidentally pull a greater version of the homonymous package from pypi.org.
There doesn't seem to be a way to deny/allow to give per package `update_cache` permissions to different users, or is there?
Ideally I'd want to deny `update_cache` entirely on a per package basis.

I've been trying pypicloud for the past weeks and this seems to be an awesome tool, extremely well suited for cloud provider environments, kudos.

**Comment by stevearc** [comment]
It's not possible the way it's currently built, but you could hack that logic in pretty easily, depending on how dirty you're willing to make the hacks 😛

You care about [access.can_update_cache](https://github.com/stevearc/pypicloud/search?q=can_update_cache&unscoped_q=can_update_cache), particularly the two in [simple.py](https://github.com/stevearc/pypicloud/blob/feae61f02d3abd734d771f4a74159b460e98063a/pypicloud/views/simple.py#L231). You have the package available at the time of that call, so you should be able to modify it to do something specific on a per-package basis.

**Comment by mamoit** [comment]
We're thinking about moving the `can_update_cache` inside the `get_fallback_packages` method in order to evaluate it on a per package basis, and thus moving the permission evaluation to a single place.
We'll make a PR if we manage to implement it in a not too hacky way that can actually be re-used by somebody else in a sane way.

Thanks for the tips :+1:

**Comment by mamoit** [comment]
Would it be interesting to get rid of the `can_update_cache` method entirely and create a new `update_cache` permission and using it as you would with `read` and `write`?
Would that require too much of a revamp?
It doesn't seem like it, but just want your 2 cents before diving into that approach.

**Comment by stevearc** [comment]
Hmmmm...yeah I think that would work. That would allow you to set it for specific packages and then if you add a `default_can_update_cache` to match the `default_read` and `default_write` config options, I think that covers all the bases.

**Comment by mamoit** [comment]
We want a way to deny certain packages instead of allowing specific ones (way easier to maintain), so @neuronist came up with the solution above :point_up:
Let us know what you think about the solution.

**Comment by stevearc** [comment]
Linked PR was merged; closing this issue
