### ISSUE TITLE
Allow Read / Write access to unauthenticated users

### ISSUE THREAD

**Issue by nshipman01** [stevearc/pypicloud#217]
Is there anyway to allow unauthenticated users read and write access to the packages on pypicloud? Currently using a setup that involves redis db backend instead of dynamodb or postgresql. 

The plan is to use ip restrictions to disable access. Thanks

**Comment by stevearc** [comment]
Yep! From the section on [Access Control](https://pypicloud.readthedocs.io/en/latest/topics/access_control.html?highlight=everyone#users-and-groups) you can see that there is a special group named `everyone`.

You can set the [read and write permissions](https://pypicloud.readthedocs.io/en/latest/topics/configuration.html#pypi-default-read) to allow that group.

```
pypi.default_read = everyone
pypi.default_write = everyone
```

**Comment by nshipman01** [comment]
Thank you Steve. Closing this issue!
