### ISSUE TITLE
[Question] Should I be concerned about any credential leak in Pypicloud install URL?

### ISSUE THREAD

**Issue by pearsonhenri** [stevearc/pypicloud#227]
Hey there! When I `pip install` install a package hosted in our private PypiCloud repository (which is awesome, btw! Been a huge fan of it :smile: ), the Pip installation output includes this log line:
```
Downloading https://s3.sa-east-1.amazonaws.com/${MY_S3_BUCKET}/88a9/lambda-inspetor/lambda_inspetor-0.0.2-py3-none-any.whl?Expires=1579181517&AWSAccessKeyId=${AWS_ACCESS_KEY_ID}&Signature=${A_SIGNATURE}&x-amz-security-token=${BIG_OLD_AMZ_SECURITY_TOKEN}
``` 
(with the variables substituted in with actual values, of course).

I'm wondering if this poses a security risk at all? Presumably the only people who would ever even see this output would be people who have authenticated using appropriate credentials to download from our Pypi instance, but does this expose any information that they might be use to, say, escalate their AWS privileges? 

To be frank I can't think of anything too sneaky they'd be able to do, but curious if other Pypicloud users have chosen to mitigate this at all by obfuscating potentially sensitive variables in the download URL.

**Comment by stevearc** [comment]
Glad to hear it's working for you! To the best of my knowledge, the signed S3 url is safe and won't expose you to any risk of people escalating AWS permissions. Your access key ID is safe to expose publicly, and the signatures are just the result of a one-way crypto hash. This is all using the standard mechanisms for [signed S3 urls](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-signed-urls.html#private-content-how-signed-urls-work). I encourage you to google around for more information on how it works and why it's safe so you can be more confident in its security
