### ISSUE TITLE
Notifiy new package or version upload to Slack

### ISSUE THREAD

**Issue by everpeace** [stevearc/pypicloud#229]
Thank you for sharing the great OSS project!

I'd like to notify new packages/versions to slack.  I'm not familiar pyramid though, I suppose `hooks` would be a solution described in #213 .

But, I'm not sure which endpoints should it subscribe to solve this. I would be much appreciated if someone would answer 🙇

**Comment by stevearc** [comment]
Hi @everpeace! The endpoint where packages are upload to is https://github.com/stevearc/pypicloud/blob/290c09ea2ea1a60f52532ea8334d613392a0add7/pypicloud/views/simple.py#L19-L22

Hopefully this will give you a good start  🙂

**Comment by everpeace** [comment]
Thanks!  I will look into it!
