### ISSUE TITLE
Bug + Fix: Unable to reload Redis cache when package has no summary

### ISSUE THREAD

**Issue by dani29** [stevearc/pypicloud#230]
Hi all,
let me start by thanking your community on the effort you take maintaining this project, which has proved very useful to me and my team. 

I came across the following bug while deploying a Pypicloud with Redis as cache, backed by GCS (though it'd apply for S3). The bug prevents from rebuilding the cache if a specific Python package has no summary. This is due to Redis' lack of support in None values in newer version of its' client.

Steps to reproduce:
redis==3.4.1
db.graceful_reload = True
1. Pre-populate a GCS bucket with a Python package that has no "description" field on its' setup.py
2. Sent GET /admin/rebuild request to the server
3. The call will return 200, but the Redis keys will only contain "set" and "package" keys, but no "summary" keys.

The exception trace is:
```
  File "/usr/local/lib/python3.6/site-packages/pypicloud/views/admin.py", line 25, in rebuild_package_list
    self.request.db.reload_from_storage()
  File "/usr/local/lib/python3.6/site-packages/pypicloud/cache/redis_cache.py", line 286, in reload_from_storage
    pipe.execute()
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 3967, in execute
    return execute(conn, stack, raise_on_error)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 3832, in _execute_transaction
    all_cmds = connection.pack_commands([args for args, options in cmds
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 796, in pack_commands
    for chunk in self.pack_command(*cmd):
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 771, in pack_command
    for arg in imap(self.encoder.encode, args):
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 121, in encode
    "bytes, string, int or float first." % typename)
redis.exceptions.DataError: Invalid input of type: 'NoneType'. Convert to a bytes, string, int or float first.
```

I've added additional logging in other places, printing the "summary" object while iterating [here](https://github.com/stevearc/pypicloud/blob/master/pypicloud/cache/redis_cache.py#L283).
The problem is that the summary object contains a None value:
 ```
INFO 2020-02-23 09:32:37,837 [pypicloud.cache.redis_cache] Summary: {'name': 'my-internal-package', 'summary': None, 'last_modified': datetime.datetime(2020, 2, 19, 13, 13, 41, 934000, tzinfo=<UTC>)}
```

The fix, in my opinion, is very straightforward. Modifying L188 [here](https://github.com/stevearc/pypicloud/blob/master/pypicloud/cache/redis_cache.py#L188) to something like `"summary": summary["summary"] or ""` would avoid trying writing a None value to Redis. I've seen a similar thing done in other places in the code, but I believe that this is the **most** correct place to perform this conversion.

I've tried to create a PR but had no push permissions to the repo.
Best,
Dani

**Comment by stevearc** [comment]
Thanks for the report! I applied your fix in the commit above.

You don't actually need push permissions to make a pull request. You can fork the repo, make the changes and push them up to your own repo, and then initiate the pull request from there. For next time!
