### ISSUE TITLE
Get statics from CDN

### ISSUE THREAD

**Issue by koleror** [stevearc/pypicloud#236]
Hey there! 
I'm trying to run pypicloud as a serverless app on AWS lambda, which works fine. 
The only problem I have is with the binary statics.
A simple fix would be to have an option to get the statics from a public CDN like cloudflare instead of the server itself. Another idea would be to store the files from S3 at deployment time and use S3 as base static domain. 
Is there any simple way to do this?
Thanks!

**Comment by stevearc** [comment]
By default, if you're using S3 as your storage backend pypicloud will serve your files from there. You actually have to set [pypi.stream_files = true](https://pypicloud.readthedocs.io/en/latest/topics/configuration.html#pypi-stream-files) to get it to serve the package binaries from the pypicloud server itself.

The default configuration is to serve the files by providing the client a signed S3 url. There's another option [storage.public_url = true](https://pypicloud.readthedocs.io/en/latest/topics/storage.html#storage-public-url) that will generate unsigned S3 urls (if your bucket is public). The advantage being that the url won't change, so pip can more easily cache the result.

There's also an option to use [Cloudfront](https://pypicloud.readthedocs.io/en/latest/topics/storage.html#cloudfront) on top of S3 to serve the files (still using signed urls).
