### ISSUE TITLE
Passwort Verification seems painfully slow

### ISSUE THREAD

**Issue by sbrandtb** [stevearc/pypicloud#237]
I have set up pypicloud and it works well so far. There is only one issue: When using logged in users, the process becomes painfully slow. Every request to pypicloud requires around 1 second, while without login it is <<100ms

I found out that this is probably the password verification algorithm which [currently only permits sha512_crypt](https://github.com/stevearc/pypicloud/blob/master/pypicloud/access/base.py#L25-L32).

In my local tests, this algorithm is painfully slow, compared to pbkdf2_sha512 (with `fastpbkdf2` installed. Without times are around doubled)

```
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.13.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from passlib import hash

In [2]: h = hash.sha512_crypt.hash('foobarbaz')

In [3]: %timeit hash.sha512_crypt.verify('foobarbaz', h)
331 ms ± 3.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

In [4]: h = hash.pbkdf2_sha512.hash('foobarbaz')

In [5]: %timeit hash.pbkdf2_sha512.verify('foobarbaz', h)
14.3 ms ± 1.25 ms per loop (mean ± std. dev. of 7 runs, 100 loops each)
```

Why don't you allow pbkdf2 or other algorithms? First [is suggested by passlib](https://passlib.readthedocs.io/en/stable/narr/quickstart.html) as one of the preferred algorithms for new applications.

I am happy to prepare a pull request if there is no reason against allowing those.

**Comment by stevearc** [comment]
I've seen a report of this before in #115. As a result of that, I added the [auth.rounds](https://pypicloud.readthedocs.io/en/latest/topics/access_control.html#auth-rounds) configuration option so you can tweak the password hashing to be as fast as you like.

At your suggestion, I just added a couple commits that do a few things:
* Add a `auth.scheme` config option where you can supply `pbkdf2`, `bcrypt`, or `argon2` as alternatives to the default sha hashing scheme
* Tuned the default number of rounds for password hashing to take significantly less time
* Added documentation about both of these things, with some discussion of why the threat model of pypicloud makes it unlikely that fast pw hashing will be an issue

**Comment by sbrandtb** [comment]
Thanks, that's more and much faster than expected! :slightly_smiling_face: 

Inevitable question: When will this be released?

**Comment by stevearc** [comment]
The `auth.rounds` option has been out for a while, but the rest of it will go out in the next release. I hope to do that in the next week or two; the only remaining item I want to get into that release is finishing up support for #219.

**Comment by sbrandtb** [comment]
@stevearc Tried out the new version. Works like a charm. Thanks!
