### ISSUE TITLE
Cache issue with packages that have same name/version but different py version

### ISSUE THREAD

**Issue by yanovs** [stevearc/pypicloud#246]
My coworkers and I have run across an issue when trying to gracefully reload the SQLite-backed cache: when a package has the same name and version, but different python version compatibility (e.g., [`docutils==0.15.2` was released this way](https://pypi.org/project/docutils/0.15.2/#files)), the server only registers one of the packages. If we set `graceful_reload=False`, the issue goes away, but we'd obviously prefer to use the graceful reload.

Here's a branch with both a simple test case that fails in master and a potential fix: https://github.com/yanovs/pypicloud/pull/1. FYI, I'm running this patched version of the server, and things look fine so far.

The potential fix is to have `pypicloud.models.Package` hash and compare based on `self.filename` rather than `self.name` and `self.version` (e.g., then `docutils-0.15.2-py2-none-any.whl` and `docutils-0.15.2-py3-none-any.whl` don't get collapsed in the set).

However, this is obviously a change to a core class of the library, so I was wondering what people thought. (Is `filename` always non-`None`? Would it be better to parse the other parts of the wheel name and include them in the hashing/comparing tuple?)

Thanks!

**Comment by stevearc** [comment]
Oh wow I must have missed this back when you submitted it. My apologies!

Turns out you're completely correct and comparing the filenames is the solution to that problem. This ended up getting reported again later and eventually fixed by #267
