### ISSUE TITLE
Set signing key via environment variable or pull from AWS or K8s secret

### ISSUE THREAD

**Issue by mercul3s** [stevearc/pypicloud#247]
I'm setting up a pypicloud instance with auth backed by an AWS secret. I want to setup user registration via tokens, and from looking at [the docs](https://pypicloud.readthedocs.io/en/latest/topics/access_control.html#auth-signing-key), it seems like I'd need to add the signing key to the config directly. I would like to avoid this as the config is in git and goes through a CI step. Is there a way to expose this value as an environment variable (outside the config) that pyramid/pypicloud would be able to pick up, or ideally, pull from another AWS secret?

**Comment by stevearc** [comment]
This would be a good use case for AWS secrets manager, but that's more heavy lifting than I'm inclined to do right now (though I would review any pull requests for it). Adding an option to pass it in as an environment variable would be pretty straightforward, though. I can add that

**Comment by mercul3s** [comment]
Great! An environment variable will solve the immediate need as we can use a k8s secret. If you have some pointers for where I'd start making changes to add support an AWS secret, I'd be happy to give it a shot when I've got some bandwidth.

**Comment by stevearc** [comment]
This is the function where we read in the settings from the config file:
https://github.com/stevearc/pypicloud/blob/7d6edff4c91fce7efc3aefe5b60e07685ad06e8a/pypicloud/access/base.py#L122

If you were using AWS secrets manager I think it would be as simple as fetching the values there and using them in place of the settings file. That would be enough to configure it on startup, but you may want to add some additional logic to refetch periodically if you expect it to change while the server is running.
