### ISSUE TITLE
Internal Server Error when package in local storage but not in fallback repository

### ISSUE THREAD

**Issue by chludwig-haufe** [stevearc/pypicloud#251]
Until now, we used our pypicloud instance (using pypicloud 1.1.1) as a caching proxy only. Today, we uploaded a package that is intended for internal use only. We then found that attempts to download this package trigger an internal server error, cf. the attached [pypicloud_stacktrace.log](https://github.com/stevearc/pypicloud/files/4886529/pypicloud_stacktrace.log).

Our pypicloud instance is configured with `pypi.fallback = cache` and `pypi.always_show_upstream = True`. (I observed the same issue with `pypi.always_show_upstream = False`, though.)

I think the issue is caused by [Line 24 of locator.py](https://github.com/stevearc/pypicloud/blob/d88016905b63859fb029b57aa452bf0f90a96df6/pypicloud/locator.py#L24) that raises an HTTP error if the package is not found in the fallback repository. However, this exception is not handled in [views/simple.py](https://github.com/stevearc/pypicloud/blob/1.1.1/pypicloud/views/simple.py) which leads to the ISE.

I deployed a patched version of `SimpleJsonLocator` in `locator.py` that returns an empty list if the response status is 4xx. AFAICT, this code is called from two functions:
1. `get_fallback_packages()` in `views/simple.py`: This function returns an empty mapping if `SimpleJsonLocator` returns an empty list - which is in line with this function description in its docstring.
2. `download_package()` in `views/api.py`: If `SimpleJsonLocator` returns an empty list, then the local variable `dist` is never updated and stays `None`. In this case `download_package()` [will return `HTTPNotFound()`](https://github.com/stevearc/pypicloud/blob/d88016905b63859fb029b57aa452bf0f90a96df6/pypicloud/views/api.py#L102) which also seems correct.

With the patched version, I can successfully download both purely local packages and packages that need to be fetched from the fallback repository. If you want me to, I can prepare a pull request. However, it might be less work for both of us if you add the simple `if` statement to line 24 of `locator.py` yourself. Whatever you prefer...

**Comment by stevearc** [comment]
I can add the check. Thanks for the report!

**Comment by chseki** [comment]
Hello, Just for report:

We are facing the same with internal packages, cf. [log](https://github.com/stevearc/pypicloud/files/4953531/pypi.log)

Our pypicloud instance has the same configuration: `pypi.fallback = cache` and `pypi.always_show_upstream = True` (using pypicloud 1.1.1)

Curiously we can download it via the web interface in route `/#/package/my-internal-package` that uses `api/pacakge/` to retrieve it. But as we use /simple/package to download packages, this is not a solution.

**Comment by leorochael** [comment]
@stevearc, thanks for addressing this issue.

Out of curiosity, and just for our internal planning, when can we expect a release with this fix?

**Comment by stevearc** [comment]
Released!
