### ISSUE TITLE
S3 custom server endpoint doesn't work

### ISSUE THREAD

**Issue by j4m3s-s** [stevearc/pypicloud#263]
storage.endpoint_url is not documented, and doesn't work on 1.1.5.

I tried to use pypicloud with custom self hosted s3 and encountered botocore errors trying to connect to AWS servers.

**Comment by stevearc** [comment]
That argument in particular isn't called out in the docs, but there is [a mention](https://pypicloud.readthedocs.io/en/latest/topics/storage.html#s3) that we attempt to support any arguments that can be passed to [resource](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html#boto3.session.Session.resource) or [Config](https://botocore.amazonaws.com/v1/documentation/api/latest/reference/config.html#botocore.config.Config).

Can you provide:
* The pypicloud storage configuration you are attempting to use
* A working example of using those arguments to connect to S3 using the boto or botocore library
* The text of the errors that you are encountering

**Comment by nivintw** [comment]
forgive me for resurrecting dead and long-open issues, but can confirm that storage.endpoint_url does indeed work correctly at least for version 1.3.7 and that it's passed down correctly.

I use the setting with localstack on my local machine for context. The specific value I have (for double checking formatting reasons) is `http://10.43.69.82:4566`
