### ISSUE TITLE
GCS access problems for downloading packages

### ISSUE THREAD

**Issue by leonoverweel** [stevearc/pypicloud#265]
Hi, thanks for setting up this project! It's exactly what we're looking for at my company to distribute our code between projects internally.

I'm trying to use PyPI Cloud on GCP and I'm running into some authentication issues. My setup, roughly following [this Medium post](https://d-tresoldi5.medium.com/deploying-a-pypi-server-in-minutes-with-gcp-17c6b0b92e79), is:
* Code is hosted on a private GitHub repository.
* The Docker container is built by Google Cloud Build, triggered by pushes to GitHub, where it pulls the code from
* The container runs as a fully managed Google Cloud Run Service.
* The caching engine is Redis, through Google Memorystore, which the Cloud Run Service has access to via a Serverless VPC Connector.
* The default service account for the Cloud Run Service has a Storage Administrator role on the GCS bucket backing PyPI Cloud.
* Everything is in `europe-west4` and on the project's `default` network.

Up to this point, everything seems to work fine: the PyPI cloud page loads, and I was able to upload a package to it with twine, which shows up both in the UI and in the GCS bucket.

The problem starts when I try to download the package, either via pip install or via the site. I get this error:

```
{"error": "unknown", "message": "you need a private key to sign credentials.the credentials you are currently using <class 'google.auth.compute_engine.credentials.Credentials'> just contains a token. see https://googleapis.dev/python/google-api-core/latest/auth.html#setting-up-a-service-account for more details."}
```

I'm guessing this worked locally because I had the service account's JSON key downloaded and had pointed the `GOOGLE_APPLICATION_CREDENTIALS` to that. However, doing this with my Cloud Build setup would require checking the private key into git, which seems like a bad idea. I was also under the impression that the Cloud Build / Run would take care of this because I gave its service account access to my GCS bucket, but apparently not.

After reading #261 and #262, I tried setting `storage.gcp_use_iam_signer = true`, creating a new service account (with Storage Administrator access to the GCS bucket, assigned to the Project Editor role in the Cloud Run Service), and setting that account as `storage.iam_signer_service_account_email`. Then my error changes to:

```
{"error": "unknown", "message": "Error calling the IAM signBytes API: b'{\\n  \"error\": {\\n    \"code\": 403,\\n    \"message\": \"The caller does not have permission\",\\n    \"status\": \"PERMISSION_DENIED\"\\n  }\\n}\\n'"}
```

I've tried a few other variations of the above (mostly different service accounts associated with the Cloud Run Service).

Any idea what's wrong with my setup, or if this is a bug / unsupported setup?

**Comment by stevearc** [comment]
Thanks for the detailed bug report! #261 did recently change the GCS signing logic, so that could possibly explain the why following the medium article didn't work exactly as printed. Unfortunately, I've never used GCP myself so most of the code here is from the community, and I don't have a great way to test it against live services. So I'll need some help to debug what's happening.

Based on the most recent error you're getting, it sounds like the service account you're using still doesn't have the correct permissions. From this link https://cloud.google.com/iam/docs/reference/credentials/rest/v1/projects.serviceAccounts/signBlob#http-request it sounds like your account needs the permission `iam.serviceAccounts.signBlob` "on the specified resource name". Do you see that permission as an option? Have you tried granting it to the signer service account?

[This post on stackoverflow](https://stackoverflow.com/questions/54271402/sign-google-cloud-storage-urls-with-google-compute-engine-default-service-accoun) mentions the same permission and also mentions the role `roles/iam.serviceAccountTokenCreator`. Maybe give that a try as well if the permission grant alone doesn't fix it?

**Comment by leonoverweel** [comment]
Thanks for the quick reply!

I thought I had tried something like that but just in case I just tried again with a new service account that I gave the `serviceAccountTokenCreator` role (I can't find a sign blob role) on top of the Storage Admin role, but sadly that didn't work. I also can't find a blob signing IAM permission on the storage bucket or the runner, not sure what's up with that.

(By the way, we've also contacted our GCP support agent to get help with this. I'm not sure how long that'll take, but if I figure it out with them I'll also post an update here.)

**Comment by stevearc** [comment]
@pPanda-beta how did you set up your configuration for the new IAM signing logic? Are there any obvious differences?

**Comment by pPanda-beta** [comment]
@stevearc 
I'm using kubernetes for deployment
I'll get back to with the configurations.

**Comment by leonoverweel** [comment]
Solved: turns out you also need to select the service account in a an "advanced" submenu of the Cloud Run service deployment configuration; that was still set to the default service account for me instead of the one that had access to GCS. Selecting the right one fixed it.

Thanks for the help!

**Comment by lgeiger** [comment]
> I'm using kubernetes for deployment. I'll get back to with the configurations.

@pPanda-beta That would be awesome!

**Comment by pPanda-beta** [comment]
Thanks @leonoverweel for grabbing our attention. 
#261  is still not fixed.

> turns out you also need to select the service account in a an "advanced" submenu of the Cloud Run service deployment configuration; that was still set to the default service account for me instead of the one that had access to GCS. Selecting the right one fixed it

This exactly what we wanted to avoid. 

What you configured there is basically the reply of : http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/?recursive=true

But in #261 we wanted `http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/<custom service account email>/?recursive=true`

**Comment by pPanda-beta** [comment]
@lgeiger 
For testing u can use docker compose: 

```yaml
version: "3.7"

services:

  redis:
    image: redis:3.2
    container_name: redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./redis-data:/data

  pypicloud:
    container_name: pypicloud
    image: stevearc/pypicloud:1.1.6-py3-alpine
    ports:
      - 8080:8080
    volumes:
      - ./configs:/etc/pypicloud

```

And configs (config.ini) as : 
```
storage.bucket: <bucket name>
storage.gcp_use_iam_signer: true
storage.prefix: pypi
storage.prepend_hash: false
storage.project: <project id>
storage.region: <region>

storage.gcp_service_account_json_filename = /etc/pypicloud/gcs-svc-account.json

```
