### ISSUE TITLE
Description/summary lost with cache

### ISSUE THREAD

**Issue by awoimbee** [stevearc/pypicloud#278]
I use kubernetes, so the more my apps are stateless, the easier and simpler it is to manage.

At first glance it looks like ground truth is in "storage" and that "cache" can be easily rebuilt.
The issue is that package summary is not stored in "storage" (well, it technically is but inside the .tar.gz files and pypicloud can't read it).

So if package summary is important to me I need to either:
- attach persistent storage that I will have to manage (these things are made for real data, not <1MiB)
- run a dedicated SQL or Redis server (for a ridiculously low amount of data)
- use DynamoDB (I need to use AWS)

**Comment by stevearc** [comment]
The intention is for all of the data to be persisted in the "storage" layer, and that the cache can be rebuilt at any time. We should be storing the package summary in the metadata of whatever storage backend is being used. For example, the S3 backend uses this method to upload packages:
https://github.com/stevearc/pypicloud/blob/71b2e349a6e0c66d41e7c290880afed4ba7cab37/pypicloud/storage/s3.py#L203-L207

If you look at the implementation of `get_metadata` in [models.py](https://github.com/stevearc/pypicloud/blob/master/pypicloud/models.py), it should be returning the summary, as well as some other info.

Have you seen any cases where the summary disappears after rebuilding the cache?

**Comment by awoimbee** [comment]
Oh ok sorry.
I lost file metadata during an S3 cross region replication/move, it's 100% my fault.
On newly uploaded package I have everything:

| type | key | value |
| -- | -- | -- |
| User defined | x-amz-meta-version | 0.1.3
| User defined | x-amz-meta-name | my_package
User defined | x-amz-meta-summary | My package short description
User defined | x-amz-meta-hash-md5 | xxxxxxxxxxxxxxxxxxxxxxx
User defined | x-amz-meta-hash-sha256 | xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

I think it would be wise to print a warning in case of missing metadata. WDYT ? Would it be an issue for [backwards compatibility](https://github.com/stevearc/pypicloud/blob/71b2e349a6e0c66d41e7c290880afed4ba7cab37/pypicloud/storage/s3.py#L134) (too many warnings on old installs) ?

BTW nice job for this project

**Comment by stevearc** [comment]
Thanks! I think I'd prefer to continue to let it pass silently. Missing metadata doesn't necessarily indicate that anything is wrong, and the server will continue to function fine as a package repository. I tend to keep my errors and warnings minimal because investigating false positives can be very costly in terms of time and effort.

**Comment by awoimbee** [comment]
Ok, closing this now.
If someone else has this issue at least they'll stumble on this thread. Maybe they will even have kept their old bucket (🥲).
