### ISSUE TITLE
Changing root context for pypicloud when using Apache as a reverse http proxy

### ISSUE THREAD

**Issue by DragonDuck** [stevearc/pypicloud#279]
Hello! I've got a bit of a peculiar problem. I'm using Apache as a reverse proxy to direct HTTPS traffic to a Docker container running a pypicloud server.

The problem is that URLs (e.g. to scripts or style sheets) aren't being correctly rendered in HTML templates.

When running without Apache (so having Docker listen directly to an open port), the URLs in the HTML templates get rendered correctly, e.g. as http://<PUBLIC_IP_ADDRESS>:<PORT>/static/1.2.0/css/base.css and the pypicloud web UI works without problems. However, when using Apache, all URLs fill in "localhost" as the URL domains, e.g. http://localhost:8080/static/1.2.0/css/base.css. Obviously, this causes problems for browsers.

As far as I can tell, this is because the Pyramid framework calls the `static_url` function to generate the full URL of the resource and uses `pypicloud.route.Root` as the root context. Is there a way to force the root to be my desired URL instead of being autogenerated? I can't find anything in the documentation about overwriting the root context, so I'm not sure this is possible.

Thank you so much!

**Comment by stevearc** [comment]
Yeah, running behind a reverse proxy is a common situation. I outlined some information in the docs: https://pypicloud.readthedocs.io/en/latest/topics/deploy.html#https-and-reverse-proxies

The link to the Paste docs is out of date (I just committed an update). You can find the new docs on the prefix middleware here: https://docs.pylonsproject.org/projects/pastedeploy/en/latest/modules/config.html#paste.deploy.config.PrefixMiddleware. You may not have to manually specify any args, actually, as simply activating this middleware will cause Pyramid to read the headers that Apache should be sending

From: https://github.com/Pylons/pastedeploy/blob/df109cacddc56af8cfe75fc7df39af6e1f2cd92d/paste/deploy/config.py#L234-L237
```
    Also, unless disabled, the ``X-Forwarded-Server`` header will be
    translated to the ``Host`` header, for cases when that header is
    lost in the proxying.  Also ``X-Forwarded-Host``,
    ``X-Forwarded-Scheme``, and ``X-Forwarded-Proto`` are translated.
```

**Comment by DragonDuck** [comment]
Oh wow, I totally overlooked that in the focs. Thank you so much!
