### ISSUE TITLE
Cannot see packages if logged in as non-admin user on pypicloud

### ISSUE THREAD

**Issue by aperuru** [stevearc/pypicloud#284]
@stevearc  I was using pypicloud version 1.1.5 until recently, at some point due to pyramid new version release I was no longer able to make new deployments. So I decided to move to 1.2.3 version.

I now see that non-admin users can no longer view or access the packages on pypicloud

I'm using S3 storage, DynamoDB caching, Secrets Manager to store secrets and service is hosted in ECS.
Let me know if you can help

**Comment by aperuru** [comment]
Hey @stevearc, thank you for a quick fix, are you going to create a new release ?

**Comment by stevearc** [comment]
Yes. I'm fighting with travis-ci right now to get it to build my changes, but a new release will be coming soon

**Comment by stevearc** [comment]
Done

**Comment by aperuru** [comment]
Awesome, thank you @stevearc . I really appreciate it for providing a fix so quickly. 🚀
