### ISSUE TITLE
Possible values for `pypi.default_write` and `pypi.default_read` 

### ISSUE THREAD

**Issue by aperuru** [stevearc/pypicloud#294]
@stevearc  I'm aware of these two options only `everyone` and `authenticate`. 
I wonder if there is any way to block the write or read access ?
So the users should not be able to write/read to/from pypicloud

**Comment by aperuru** [comment]
so its a group name? 
How to allow only admins to perform read/write?

**Comment by stevearc** [comment]
As mentioned [in the docs](https://pypicloud.readthedocs.io/en/latest/topics/configuration.html#pypi-default-read), `pypi.default_read` and `pypi.default_write` are both a list of groups. You can use the `admin` group to restrict it to only admin users:

```ini
pypi.default_read = admin
pypi.default_write = admin
```

**Comment by aperuru** [comment]
Thank you for your response.
