### ISSUE TITLE
Cannot create user from the web UI

### ISSUE THREAD

**Issue by jonjesse** [stevearc/pypicloud#296]
From Admin page, I click on "Create user", but there's no option to submit!

I see a "Username" and "Password" forms, but no submit button.

**Comment by stevearc** [comment]
Oof, yeah this was made quite a while ago (using a now-very-outdated version of angular) and the UI is not good. There is no submit button, but if you press "enter" it should create the user

**Comment by jonjesse** [comment]
Thanks much! There are a few more options where pressing "enter" works, appreciate the help
