### ISSUE TITLE
Support redis-cluster as a cache option

### ISSUE THREAD

**Issue by YannayH** [stevearc/pypicloud#308]
Hello!

I think it would be great if pypicloud would support redis-cluster, in order to work with high load and high performant setups.

The changes needed are adding an option to the redis configuration whether or not the redis is clustered, and if so - in the code, use the RedisCluster class instead of StrictRedis, as in newer versions of redis python package there is support for Redis in clustered mode.
The interface of the classes is the same, and the code won’t need to change much.

Would love for the support in order to create huge pypicloud instances holding hundred thousand of packages.

Thanks!

**Comment by stevearc** [comment]
Sounds like a pretty straightforward change. I would happily review a PR for it!

**Comment by YannayH** [comment]
Opened #309 
Would love a review :D

**Comment by YannayH** [comment]
Hey @stevearc 
Can you release a new version of the package and build a new docker image?

**Comment by stevearc** [comment]
New release is out, and docker images are being uploaded
