### ISSUE TITLE
Add ability to rebuild package list without first purging it

### ISSUE THREAD

**Issue by patricklucas** [stevearc/pypicloud#67]
I'm trying to upgrade from a simpler PyPI server that was backed by a directory populated from S3. Our workflow involves uploading new packages to an S3 bucket, where they are synced to each PyPI server using S3 ObjectCreate notifications.

My first pass using pypicloud was going to involve just hitting the 'rebuild index' endpoint whenever a new package is uploaded, but it seems that that purges the entire cache first. This would cause downtime which would result in build failures.

One possibility is to change the behavior of /admin/rebuild to be diff-oriented, adding metadata for any new packages and removing metadata for packages that no longer exist, instead of purging the cache and starting over.

Another could be to add an endpoint that would notify pypicloud of a newly-added package file so it can be indexed incrementally.

Regardless, I think having a non-destructive full-refresh option would be an asset—it would be nice to be able to periodically ensure the cache is in sync with the datastore without causing downtime.

**Comment by pkoch** [comment]
Hi, Steve!

I started off with testing your version, and it eventually evolved to be what's on https://github.com/mathcamp/pypicloud/pull/69

i've also tried *really* hard to make this play well with things changing from under it. Namely, I don't want this to stumble if a new package comes in during a rebuild.

Take a look at things, let me know your opinions!

**Comment by ghTravis** [comment]
When is this going to be implemented? The rebuild command really kills the pipeline we have going as well, especially when you run pypicloud across many regions and each one has its own cache.

I like the idea that @patricklucas has where you use S3 CreateObject notifications, that's a good one.

**Comment by pkoch** [comment]
Hi! Left Yelp meanwhile, never got back to this (sorry, @stevearc! x-/ ). The more relevant parts of the change we eventually shipped are (in this order):
* https://github.com/Yelp/pypicloud/pull/2/files
* https://github.com/Yelp/pypicloud/pull/3/files

https://github.com/Yelp/pypicloud/pull/2/files defines a command, ``, that we hooked up to get the event from S3. Sorry, I can't seem to find that glue code. :/

**Comment by stevearc** [comment]
One of the difficulties with the diff-based approach was maintaining consistency with the 'stable' and 'unstable' version numbers in the package summary. I just released [1.0.0rc1](https://pypi.python.org/pypi/pypicloud/1.0.0rc1) which (among other things) removes those version numbers. It should be much easier to make that work now.

**Comment by stevearc** [comment]
Released [1.0.0rc2](https://pypi.python.org/pypi/pypicloud/1.0.0rc2) which contains a `db.graceful_reload` option, which should keep the cache usable while syncing with S3. It also contains [some tools](http://pypicloud.readthedocs.io/en/1.0/topics/s3_sync.html#s3-sync) for setting up an AWS Lambda function that syncs caches using the S3 Create/DeleteObject notifications.

**Comment by thehesiod** [comment]
I'm seeing an issue were with `graceful_reload` on and off and it's not repopulating the sqlite database.  It seems it makes it to the ORM merge method but then nothing gets added to the DB.  I'll continue investigating tomorrow.

**Comment by stevearc** [comment]
Hmmmm...I have occasionally seen people have issues with the DB transaction system; I wonder if it's related to that. Let me know if you manage to find a consistent repro.

**Comment by stevearc** [comment]
Closing with the assumption that the now-default graceful reload behavior solves this issue. Open a new issue if this is not the case
