### ISSUE TITLE
Nginx config missing ssl configuration

### ISSUE THREAD

**Issue by ghost** [stevearc/pypicloud#89]
http://pypicloud.readthedocs.io/en/latest/topics/deploy.html#wsgi-server

Just listens on port 80, but the _Note_ below targets http**s**://username:password@pypi.myserver.com/pypi/

Here is my config:

```
server {
    listen 80;
    server_name _;
    location / {
        include uwsgi_params;
        uwsgi_pass 127.0.0.1:3031;
    }
}

server {
    listen 443;
    server_name _;
    ssl on;
    location / {
        include uwsgi_params;
        uwsgi_pass 127.0.0.1:3031;
    }
    ssl_certificate /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;
}
```

**Comment by stevearc** [comment]
Removed the nginx configuration from that area of the docs for simplicity. I don't want to stray too far into giving people advice about software outside the scope of pypicloud
