### ISSUE TITLE
The webui are not showing the numpy version

### ISSUE THREAD

**Issue by robsonpeixoto** [stevearc/pypicloud#96]
It do not show in the first page:
![image](https://cloud.githubusercontent.com/assets/124390/16935346/07e328dc-4d35-11e6-9af8-47cf08248d36.png)

But show in the internal page:
![image](https://cloud.githubusercontent.com/assets/124390/16935361/295d3c8c-4d35-11e6-84df-e355642e2e44.png)

The cache are woking very well

**Comment by robsonpeixoto** [comment]
The same happens with scipy package

**Comment by stevearc** [comment]
Oh, good! Someone reported this a while ago but I was unable to reproduce it. I'll give it a try with numpy & scipy and see if I can track it down this time
