### ISSUE TITLE
Can't upload to my custom pypicloud

### ISSUE THREAD

**Issue by Jake-Smullin** [stevearc/pypicloud#98]
When I register I get a 400: Bad Request, when I upload I get a 403: Forbidden. Works with pypi test server. I have credentials setup, and can access my UI. Haven't messed around with access controls, could be an issue there?

**Comment by Jake-Smullin** [comment]
This is my config.ini

```
[app:main]
use = egg:pypicloud

pyramid.reload_templates = false
pyramid.debug_authorization = false
pyramid.debug_notfound = false
pyramid.debug_routematch = false
pyramid.default_locale_name = en

pypi.storage = s3
storage.bucket = eadp-pypi-cloud
storage.redirect_urls = true

# user:eadp;password:cloud
pypi.auth = config
user.eadp = $6$rounds=1000$Hr9H7PjFWqqPUScs$uVV92eE/KV6V3GteHLkF/UjhVBgXnAKvDRn.WHk7lxWtuUfz28rQF2Yl0eChB2OlqSBfpcCy8ONNyUk7jYh.g1

# db is used for caching
db.url = sqlite:////var/lib/pypicloud/db.sqlite

# For beaker
session.encrypt_key = replaceme
session.validate_key = replaceme
session.secure = false

###
# wsgi server configuration
###

[uwsgi]
paste = config:%p
paste-logger = %p
master = true
processes = 20
reload-mercy = 15
worker-reload-mercy = 15
max-requests = 1000
virtualenv = /env
http = 0.0.0.0:8080

###
# logging configuration
# http://docs.pylonsproject.org/projects/pyramid/en/latest/narr/logging.html
###

[loggers]
keys = root, boto

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console
```

**Comment by Jake-Smullin** [comment]
This is my .pypirc under `~/.pypirc`
```
[distutils]
index-servers = pypicloud

[pypicloud]
repository:https://pypi.darkside.ea.com
username:*****
password:*****
```

**Comment by Jake-Smullin** [comment]
Added ***** where user/password sensitive info was.

**Comment by Jake-Smullin** [comment]
And these are the outputs from a register and upload command.
```
jacobs@jacobs-work-computer:~/git/my-package$ python setup.py register -r pypicloud
running register
running check
Registering mypackage to https://pypi.darkside.ea.com
Server response (400): Bad Request
```
```
jacobs@jacobs-work-computer:~/git/my-package$ python setup.py sdist upload -r pypicloud
running sdist
running check
warning: sdist: manifest template 'MANIFEST.in' does not exist (using default file list)

package init file 'mypackage/__init__.py' not found (or not a regular file)
writing manifest file 'MANIFEST'
creating mypackage-0.1
making hard links in mypackage-0.1...
hard linking README -> mypackage-0.1
hard linking setup.cfg -> mypackage-0.1
hard linking setup.py -> mypackage-0.1
Creating tar archive
removing 'mypackage-0.1' (and everything under it)
running upload
Submitting dist/mypackage-0.1.tar.gz to https://pypi.darkside.ea.com
Upload failed (403): Forbidden
error: Upload failed (403): Forbidden
```

**Comment by Jake-Smullin** [comment]
I'm assuming my access controls aren't setup properly, I wasn't the one to setup our pypi cloud but I'm tasked with fixing it, and we'd like to be able to use the CLI with its desired behavior, the UI seems to be working I can login, fetch or upload a file.

**Comment by Jake-Smullin** [comment]
Note when I change my `.pypirc` to incorrect user and password the output of an upload is now unauthorized:
```
jacobs@jacobs-work-computer:~/git/my-package$ python setup.py sdist upload -r pypicloud
running sdist
running check
warning: sdist: manifest template 'MANIFEST.in' does not exist (using default file list)

package init file 'mypackage/__init__.py' not found (or not a regular file)
writing manifest file 'MANIFEST'
creating mypackage-0.1
making hard links in mypackage-0.1...
hard linking README -> mypackage-0.1
hard linking setup.cfg -> mypackage-0.1
hard linking setup.py -> mypackage-0.1
Creating tar archive
removing 'mypackage-0.1' (and everything under it)
running upload
Submitting dist/mypackage-0.1.tar.gz to https://pypi.darkside.ea.com
Upload failed (401): Unauthorized
error: Upload failed (401): Unauthorized
```
Still a 400: Bad Request from a register though.

**Comment by stevearc** [comment]
Yeah it looks like the access control is just set up to not allow that user to upload packages. The docs for access control via config file are [here](http://pypicloud.readthedocs.io/en/latest/topics/access_control.html#config-file), but there are a couple ways to go about setting it up properly.

You could give all users the ability to upload any package. (I don't know your situation, but if I had to guess I'd say this is probably what you want) [docs](http://pypicloud.readthedocs.io/en/latest/topics/configuration.html#pypi-default-write)
```pypi.default_write = authenticated```

You could make your user an admin. [docs](http://pypicloud.readthedocs.io/en/latest/topics/access_control.html#auth-admins)
```auth.admins = myuser```

You could give that specific user read/write permissions to that specific file. [docs](http://pypicloud.readthedocs.io/en/latest/topics/access_control.html#package-package-user-user)
```package.MyPackageName.user.MyUserName = rw```

Or define a group of users and give write access to all members of that group. [docs](http://pypicloud.readthedocs.io/en/latest/topics/access_control.html#group-group)
```
group.mygroup = myuser
pypi.default_write = mygroup
```

Let me know if you have any issues

**Comment by stevearc** [comment]
Oh forgot to mention that there's no need to register a package before uploading it. I never implemented that feature because it didn't fit in with the rest of the access control scheme being defined entirely server-side.
